name: Build Kernel

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  determine_targets:
    name: Set targets
    runs-on: ubuntu-latest
    outputs:
      targets_subtargets: ${{ steps.find_targets.outputs.targets_subtargets }}
      targets: ${{ steps.find_targets.outputs.targets }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set targets
        id: find_targets
        run: |
          ALL_TARGETS="$(perl ./scripts/dump-target-info.pl targets 2>/dev/null)"
          JSON_TARGETS_SUBTARGETS='["ath79/generic","ath79/nand","ramips/mt7621","ramips/mt7620","ipq40xx/generic","sunxi/cortexa53","mediatek/filogic","x86/64"]'
          JSON_TARGETS=$JSON_TARGETS_SUBTARGETS

          echo -e "\n---- targets to build ----\n"
          echo "$JSON_TARGETS_SUBTARGETS"
          echo -e "\n---- targets to build ----\n"

          echo -e "\n---- targets to check patch ----\n"
          echo "$JSON_TARGETS"
          echo -e "\n---- targets to check patch ----\n"

          echo "targets_subtargets=$JSON_TARGETS_SUBTARGETS" >> $GITHUB_OUTPUT
          echo "targets=$JSON_TARGETS" >> $GITHUB_OUTPUT

  build:
    name: Build Kernel with external toolchain
    needs: determine_targets
    permissions:
      contents: read
      packages: read
      actions: write
    strategy:
       fail-fast: False
       matrix:
         include: ${{fromJson(needs.determine_targets.outputs.targets_subtargets)}}
    uses: ./.github/workflows/build.yml
    with:
      container_name: toolchain
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
      build_kernel: true
      build_all_kmods: true
      upload_ccache_cache: ${{ github.repository_owner == 'openwrt' }}

  check-kernel-patches:
    name: Check Kernel patches
    needs: determine_targets
    permissions:
      contents: read
      packages: read
    strategy:
       fail-fast: False
       matrix:
         include: ${{fromJson(needs.determine_targets.outputs.targets)}}
    uses: ./.github/workflows/check-kernel-patches.yml
    with:
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}

  upload-ccache-cache-in-s3:
    if: github.event_name == 'push' && github.repository_owner == 'openwrt'
    name: Upload ccache cache to s3
    needs: [determine_targets, build]
    strategy:
       fail-fast: False
       matrix:
         include: ${{fromJson(needs.determine_targets.outputs.targets_subtargets)}}
    secrets:
      s3_access_key: ${{ secrets.GCS_S3_ACCESS_KEY }}
      s3_secret_key: ${{ secrets.GCS_S3_SECRET_KEY }}
    uses: ./.github/workflows/upload-file-s3.yml
    with:
      endpoint: https://storage.googleapis.com
      bucket: openwrt-ci-cache
      download_id: ${{ matrix.target }}-${{ matrix.subtarget }}-ccache-cache
      filename: ccache-kernel-${{ matrix.target }}-${{ matrix.subtarget }}.tar
